# Spring Boot application properties
server.port=8080

# --- M-Pesa (Safaricom) Sandbox Configuration ---
# For testing - Replace with your actual sandbox credentials from Safaricom Developer Portal
mpesa.consumer-key=Hu2Ziq60wttgf2fIrGAyr5kMyFzCKG4yR1PSSNv3dTIxkaOc
mpesa.consumer-secret=9GtoKEGDRSG0vTPchK3zy3oJt6hUfKxRxlMgUPsxW8Qtz1Q4GqUK8X0rasAjCUDO
mpesa.shortcode=174379
mpesa.passkey=bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919
mpesa.callback-url=http://localhost:8080/api/mpesa/callback
mpesa.environment=sandbox
mpesa.base-url=https://sandbox.safaricom.co.ke

